import type { FilterKey } from '@/lib/restrooms/filters';
import { supabase } from '@/lib/supabase';
import type { AccessType, Restroom, RestroomInfo } from '@/lib/types';

export type NearbyParams = {
  lat: number;
  lng: number;
  limit: number;
  offset: number;
  sort: string;
  filters: Partial<Record<FilterKey, boolean>>;
};

const milesFromMeters = (m: number | null | undefined) => (m != null ? m / 1609.34 : null);

// Finder RPC (nearby_restrooms_v2) → rows with `dist` in miles.
export async function fetchNearby({ lat, lng, limit, offset, sort, filters }: NearbyParams): Promise<Restroom[]> {
  const { data, error } = await supabase.rpc('nearby_restrooms_v2', {
    in_lat: lat,
    in_lng: lng,
    in_limit: limit,
    in_offset: offset,
    p_sort: sort,
    ...filters,
  });
  if (error) throw error;
  return (data ?? []).map((r: any) => ({ ...r, dist: milesFromMeters(r.dist_m) }));
}

// Fallback un-located list (before we have the user's location).
export async function fetchRestroomPage(offset: number, limit: number): Promise<Restroom[]> {
  const { data, error } = await supabase
    .from('restrooms')
    .select('id,name,lat,lng,address,hours,access_type,accessible,unisex,changing_table,requires_code,purchase_required')
    .range(offset, offset + limit - 1);
  if (error) throw error;
  return (data ?? []).map((r: any) => ({ ...r, dist: null }));
}

// Nearest restroom id within `maxMeters` — used by compose to auto-link a log.
export async function fetchNearestId(lat: number, lng: number, maxMeters = 60): Promise<string | null> {
  const { data } = await supabase.rpc('nearby_restrooms', { in_lat: lat, in_lng: lng, in_limit: 1, in_offset: 0 });
  const near = data?.[0];
  return near?.dist_m != null && near.dist_m <= maxMeters ? (near.id as string) : null;
}

export async function fetchRestroomInfo(id: string): Promise<RestroomInfo | null> {
  const { data } = await supabase
    .from('restrooms')
    .select('directions,hours,description,purchase_required,requires_code')
    .eq('id', id)
    .single();
  return data;
}

export async function updateRestroom(id: string, patch: Record<string, unknown>) {
  const { error } = await supabase.from('restrooms').update(patch).eq('id', id);
  if (error) throw error;
}

export type NewRestroom = {
  name?: string | null;
  lat: number;
  lng: number;
  address?: string | null;
  access_type?: AccessType | null;
  accessible?: boolean | null;
  unisex?: boolean | null;
  changing_table?: boolean | null;
  requires_code?: boolean | null;
  purchase_required?: boolean | null;
  directions?: string | null;
  added_by: string;
};

// `geog` is generated by a DB trigger from lat/lng — never send it.
export async function createRestroom(input: NewRestroom): Promise<string> {
  const { data, error } = await supabase.from('restrooms').insert(input).select('id').single();
  if (error) throw error;
  return data.id as string;
}
